version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - 8080:8080
    nginx:
        restart: always
        build:
            context: ./server
        ports:
            - 80:80